# IntelliJ Platform Artifacts Repositories
# https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = com.async-inspect
pluginName = async-inspect-intellij-plugin
pluginVersion = 0.1.0

# Supported build number ranges and IntelliJ Platform versions
# https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html

pluginSinceBuild = 233
pluginUntilBuild = 241.*

# IntelliJ Platform Properties
# https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#intellij-extension

platformType = IC
platformVersion = 2023.3

# Plugin Dependencies
# https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html

platformPlugins = org.rust.lang:0.4.205.5318-233

# Gradle Releases
# https://github.com/gradle/gradle/releases

gradleVersion = 8.2

# Kotlin
kotlin.code.style = official
